DROP TABLE IF EXISTS entitlement_audit_logs;
DROP TABLE IF EXISTS iap_webhook_events;
DROP TABLE IF EXISTS redemption_account_usage;
DROP TABLE IF EXISTS redemption_campaign_usage;
DROP TABLE IF EXISTS redemptions;
DROP TABLE IF EXISTS entitlement_grants;
DROP TABLE IF EXISTS iap_subscriptions;
DROP TABLE IF EXISTS iap_orders;
DROP TABLE IF EXISTS users;
